language: cpp
dist: xenial

before_script:
- sudo apt-get update
- sudo apt-get install -y build-essential
- sudo apt-get install -y qtcreator
- sudo apt-get install -y qt5-default
- qmake -v
script:
- qmake Qontainer.pro -spec linux-g++
- make
notifications:
webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
